### ISSUE TITLE
Expand on scope operator

### ISSUE THREAD

**Issue by pimentel** [guillaumechaumet/autocomplete-R#4]
I'm not sure how simple this is, but I think it would be very cool if you could have package specific scoping of the autocompletions. For example:

```{r}
dplyr::fil
```

Would give you an expansion of `dplyr::filter`, `dplyr::filter_` and not any other `filter` functions.

**Comment by guillaumechaumet** [comment]
@pimentel Perhaps the solution is like in autocomplete_python, Rstudio or R.app:
the autocomplete-R package created a connection between R and Atom
Each new entry like `dplyr::fil` ask to R (in backend) to complete info from available packages and objects

I investigated utils::rcompgen with no success
@pimentel : do you want a 'push' right?

Thanks for your interest.

**Comment by pimentel** [comment]
@guillaumechaumet push access would be great -- thank you!

thanks for the response. I will continue looking at some of the R internals for some guidance.
